### ISSUE TITLE
RPM Package

### ISSUE THREAD

**Issue by Arkelis** [hyakosm/simple_dnf#1]
Salut, je viens de découvrir ton outil alors que je m'apprétais moi-même à faire la même chose (en Python avec pygobject) ! Ca me ferait plaisir de t'aider ! Je connais un peu l'empaquetage rpm et je comptais de toute façon apprendre à faire des apps GTK en Python ! :)

Je trouvais pas comment te contacter sur ton site du coup je poste le message en issue ;)

**Comment by mayafeur** [comment]
Coucou ! Merci pour ton message ! Tu peux me contacter par mail si tu préfères : hyakosm [at] free.fr
